language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - "master"
    - "js-tests"

email: kevinkhill@gmail.com

cache:
  directories:
    - vendor
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install

before_script:
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - composer install --no-progress
  - npm install

script:
  #- php -i | grep timezone
  - phpunit -c configs/phpunit.xml.dist
  - npm test

after_script:
  - php vendor/bin/coveralls
