language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - "master"
    - "2.5"

email: kevinkhill@gmail.com

before_script:
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs
  - composer install --no-progress

script:
  - php -i | grep timezone
  - phpunit -c configs/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
