language: php

php:
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: 5.5

branches:
  only:
    - master
    - v2.0

before_script:
  #- composer selfupdate (errors with travis)
  - composer update --prefer-dist

email: kevinkhill@gmail.com

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.dist.xml

after_script:
  - php vendor/bin/coveralls
