language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - "master"
    - "2.4"

before_script:
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - date
  - composer install --prefer-dist --no-progress --no-dev

email: kevinkhill@gmail.com

script:
  - mkdir -p build/logs
  - phpunit -c configs/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
