parameters:
    khill.lavacharts.class: Khill\Lavacharts\Lavacharts
    khill.lavacharts.twig: Khill\Lavacharts\Symfony\Bundle\Twig\LavachartsExtension

services:
    khill.lavacharts:
        class: %khill.lavacharts.class%

    khill.lavacharts.twig_extension:
        class: %khill.lavacharts.twig%
        public: false
        arguments: ['@khill.lavacharts']
        tags:
            - { name: twig.extension }
