parameters:
    khill.lavacharts.class: Khill\Lavacharts\Lavacharts
    khill.lavacharts.twig: Khill\Lavacharts\Symfony\Bundle\LavachartsTwigExtension

services:
    khill.lavacharts:
        class: %khill.lavacharts.class%
        arguments: ['@twig']

    khill.lavacharts.twig_extension:
        class: %khill.lavacharts.twig%
        public: false
        tags:
            - { name: twig.extension }
